<?xml version="1.0" encoding="UTF-8" ?>
<testsuites errors="0"
            failures="1"
            tests="1">

  <testsuite name="signUpTest.signUpTest_TC06_PhoneExists" id="signUpTest.signUpTest_TC06_PhoneExists"
    errors="0" failures="1" hostname="" package="signUpTest" skipped="0"
    tests="1" time="15.09" timestamp="">
  
    <testcase name="TC_06 - Đăng ký với số điện thoại đã tồn tại" classname="signUpTest.signUpTest_TC06_PhoneExists" time="15.08" assertions="8">

    

    

    

    

    

    

      <failure message="❌ Đăng ký với số điện thoại đã tồn tại nhưng lại báo thành công (BUG)">    at NightwatchAPI.&lt;anonymous&gt; (C:\Users\phamx\Documents\Baitapnhung\nightwatch-project\tests\signUpTest\signUpTest_TC06_PhoneExists.js:41:26)</failure>

    
    </testcase>
  

  

    

  
  </testsuite>
</testsuites>
